version: "3.9"
services:
  api:
    container_name: example-api
    ports:
      - "3000:${PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URI: root:mysql@tcp(mysql:3306)/example-db?parseTime=true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - example-network
  mysql:
    container_name: example-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=example-db
      - MYSQL_ROOT_PASSWORD=mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - example-network
networks:
  example-network:
    driver: bridge
